config/routes.rb
Rails.application.routes.draw do
  get 'cards', to: 'cards#index'
  post 'cards', to: 'cards#create'
  get 'cards/:id', to: 'cards#show', as: :card
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def create
    @card = Card.new(card_params)

    if @card.save
      redirect_to card_path(@card)
    else
      render :index
    end
  end

  def show
    @card = Card.find(params[:id])

    render :show
  end

  private

  def card_params
    params.require(:card).permit(:credit_card_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
  def display_card!(card)
    if visa_or_mastercard?(card) == 'no card matched !'
      result = visa_or_mastercard?(card)
    end

    if valid_card?(card) == 'correct'
      card_type = "Your card is a #{visa_or_mastercard?(card)} "
      valid_card = "and this is a <span class='text-success'>#{valid_card?(card)}</span> card !"
      result = ("#{card_type}#{valid_card}").html_safe
    else
      card_type = "Your card is probably a #{visa_or_mastercard?(card)} "
      valid_card = "but this is a <span class='text-danger'>#{valid_card?(card)}</span> card !"
      result = ("#{card_type}#{valid_card}").html_safe
    end
    return result
  end

  def visa_or_mastercard?(card)
    if card.delete(' ').start_with?('4')
      return 'Visa'
    elsif card.delete(' ').start_with?('5')
      return 'Mastercard'
    else
      return 'No card matched !'
    end
  end

  def valid_card?(card)
    return false if card.empty?

    arr_card = card.delete(' ').split('').map! { |digit| digit.to_i }

    even_index = arr_card.values_at(-1, -3, -5, -7, -9, -11, -13, -15)
    odd_index = arr_card.values_at(-2, -4, -6, -8, -10, -12, -14, -16)

    odd_index.map! { |digit| digit * 2 }.map! { |digit| digit > 9 ? digit.digits.sum : digit }

    sum = even_index.sum + odd_index.sum

    sum.modulo(10).zero? ? 'correct' : 'wrong'
  end
end

app/views/cards/index.html.erb
<div class="container">

  <div class="main-block mt-5">

    <div class="title">
      <h3>Welcome to Credit Card Checker</h3>
      <p>With the form below you can check the availability of your credit card</p>
    </div>

    <div class="credit-card-form">
      <form action="/cards" method="post">
        <div class="form-inline">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <input type="text" name=card[credit_card_number] placeholder="Your credit card number here" class="form-control" id="credit-card-number" >
          <button type="submit" class="btn btn-primary ml-2">Check</button>
        </div>
      </form>
    </div>

  </div>

</div>

app/views/cards/show.html.erb
<div class="title mt-5">
  <h1><%= display_card!(@card.credit_card_number) %></h1>
  <%= link_to "Back", cards_path, :class => "btn btn-secondary mt-3" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CreditCardChecker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>